-- Baseline schema matching OrderEntity as of the Flyway migration to order-service
-- (previously managed by spring.jpa.hibernate.ddl-auto=update).

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_number   VARCHAR(255) NOT NULL,
    status         VARCHAR(255),
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    creation_time  TIMESTAMP(6) NOT NULL,
    update_time    TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uk_orders_order_number UNIQUE (order_number),
    CONSTRAINT ck_orders_status CHECK (status IN ('CREATED', 'PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELED'))
);
