-- Baseline schema matching UserProfileEntity and PendingRegistrationEntity as of the
-- Flyway migration to profile-service (previously managed by spring.jpa.hibernate.ddl-auto=update).

CREATE TABLE user_profiles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id        VARCHAR(255) NOT NULL,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    email          VARCHAR(255),
    mobile_number  VARCHAR(255),
    gender         VARCHAR(255),
    age            INTEGER,
    enabled        BOOLEAN NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id),
    CONSTRAINT uk_user_profiles_user_id UNIQUE (user_id),
    CONSTRAINT uk_user_profiles_email UNIQUE (email),
    CONSTRAINT ck_user_profiles_gender CHECK (gender IN ('MALE', 'FEMALE'))
);

-- Shares its primary key with user_profiles (1:1, see PendingRegistrationEntity#userProfile
-- @MapsId): no identity generation, id is assigned from the associated UserProfileEntity.
CREATE TABLE pending_registrations (
    id                  BIGINT NOT NULL,
    confirmation_token  VARCHAR(255) NOT NULL,
    token_expiry        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    confirmation_type   VARCHAR(255) NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_pending_registrations PRIMARY KEY (id),
    CONSTRAINT uk_pending_registrations_confirmation_token UNIQUE (confirmation_token),
    CONSTRAINT ck_pending_registrations_confirmation_type CHECK (confirmation_type IN ('EMAIL', 'MOBILE')),
    CONSTRAINT fk_pending_registrations_user_profiles FOREIGN KEY (id) REFERENCES user_profiles (id)
);
